ActionsWithMatrix/Controllers/MatrixController.cs
using System.Threading.Tasks;
using ActionsWithMatrix.DTO;
using ActionsWithMatrix.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ActionsWithMatrix.Controllers
{
    public class MatrixController : Controller
    {
        private readonly IActionsWithCSV _actionsWithCSV;
        private readonly IMatrixService _actionsWithMatrix;

        public MatrixController(IActionsWithCSV actionsWithCSV, IMatrixService actionsWithMatrix)
        {
            _actionsWithCSV = actionsWithCSV;
            _actionsWithMatrix = actionsWithMatrix;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _actionsWithCSV.GetArrayFromCSV());
        }

        [HttpGet]
        public async Task<JsonResult> GetMatrixFromCsv()
        {
            return Json(new { matrix = await _actionsWithCSV.GetArrayFromCSV() });
        }


        [HttpGet]
        public async Task<JsonResult> GenerateMatrix()
        {
            return Json(new { matrix = await _actionsWithMatrix.Generate() });
        }

        [HttpPost]
        public async Task<JsonResult> GetRotatedMatrix(MatrixDTO matrix)
        {
            return Json(new { matrix = await _actionsWithMatrix.Rotate(MatrixDTO.ConversionArray(matrix.ToArray)) });
        }
    }
}

ActionsWithMatrix/Views/Matrix/Index.cshtml
@using ActionsWithMatrix.DTO
@model MatrixDTO

<style>
    td {
        padding: 10px;
    }
</style>

<table border="1" rules="all">
    <tbody>
        @{
            int column = 0;
            int row = 0;
            foreach (int curr in Model.MatrixType)
            {
                column++;

                @if (column == 0)
                {
                    @:<tr>
                    }

                <td style="padding:10px">@curr</td>
                @if (column == Math.Sqrt(Model.MatrixType.Length))
                {
                @:</tr>
                row++;
                column = 0;
            }
            }
        }
    </tbody>
</table>
@using (Html.BeginForm("Index", "Matrix", FormMethod.Get, new { id = "import" }))
{
    <div class="frame" id="area">
        <button type="submit"> Import From CSV </button>
    </div>
}

@using (Html.BeginForm("Index", "Matrix", FormMethod.Get, new { id = "generate" }))
{
    <div class="frame" id="area">
        <button type="submit">Generate Matrix</button>
    </div>
}

@using (Html.BeginForm("Index", "Matrix", FormMethod.Post, new { id = "rotate" }))
{
    <div class="frame" id="area">
        <button type="submit">Rotate Matrix</button>
    </div>
}


@section Scripts {
    <script>
        function outputMatrix(data) {
            $("tbody tr").remove();
            data.map(function (matrix, i) {
                $("tbody").append("<tr data-row='" + i + "'>");
                matrix.map(function (line) {
                    $("tbody tr[data-row=" + i + "]").append("<td>" + line + "</td>");
                });
                $("tbody").prepend("</tr>");
            });
        }
        
        $(window).ready(function () {
                        $("#import").submit(function (e) {
                e.preventDefault();
                $.get("@Url.Action("GetMatrixFromCsv", "Matrix")", function (data) {
                    if (data) {
                        console.log(data);
                        matrix = data;
                        outputMatrix(data.matrix.matrixType);
                    }
                });
            });
                 $("#generate").submit(function (e) {
                     e.preventDefault();
                    
                    $.get("@Url.Action("GenerateMatrix", "Matrix")", function (data) {
                        if (data) {
                            outputMatrix(data.matrix.matrixType);
                        }
                    });
            });

            $("#rotate").submit(function (e) {
                e.preventDefault();
                var array = [];
                $("tbody tr td").map(function () {
                    array.push(+$(this).text());
                });
                $.post("@Url.Action("GetRotatedMatrix", "Matrix")", {
                    toarray: array
                        }, function (data) {
                        if (data) {
                            outputMatrix(data.matrix.matrixType);
                        }
                    });
                });
        });
    </script>
}

ActionsWithMatrix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ActionsWithMatrix</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ActionsWithMatrix</a>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()

    </div>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>